routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/websiteDeals', 'HomeController@websitedeal');
Route::get('/deal/{category}/{id}', 'DealController@dealsInCategory');
Route::get('/product/{category}/{id}', 'ProductController@productsInCategory');
Auth::routes();
Route::get('/logout', function(){
    if (Auth::user()) {
     Auth::logout();
     return view('welcome');
  }
});
Route::get('/dashboard','HomeController@dashboard');
Route::get('/home', 'HomeController@index');
Route::get('/cart', 'HomeController@cart');
Route::get('/contact', 'FrontController@contact');
Route::post('/sendMail', 'FrontController@sendMail');
Route::post('/order/address-contact', 'OrdermetaController@addressescontacts');
Route::get('/favourite/{type}','FavouriteController@favourites');
Route::get('/reviewandrating/{id}/{type}','ReviewandratingController@reviewrate');
Route::get('/flaged/{type}','FlagController@flaged');
Route::get('/websiteBids','BidController@websiteBids');
Route::get('/user/{id}/statusNeedChange','UserController@statusNeedChange');
Route::get('/getBids/{assetbid_id}', 'BidController@getBids');
Route::get('/assetbid/viewDetails/{assetbid_id}', 'BidController@getBidsOfAsset');
Route::post('/addMapLink', 'UserController@addMapLink');
Route::post('/deleteGoogleMapsLink', 'UserController@deleteGoogleMapsLink');
Route::resource('/users', 'UserController');
Route::resource('/addresses','AddressController');
Route::resource('/category','CategoryController');
Route::resource('/contacts','ContactController');
Route::resource('/deals','DealController');
Route::resource('/favourite','FavouriteController');
Route::resource('/media','MediaController');
Route::resource('/message','MessageController');
Route::resource('/messagemedia','MessagemediaController');
Route::resource('/order','OrdermetaController');
Route::resource('/products','ProductController');
Route::resource('/reviewandrating','ReviewandratingController');
Route::resource('/subcategory','SubcategoryController');
Route::resource('/support','SupportController');
Route::resource('/supportmedia','SupportmediaController');
Route::resource('/productindeals','ProductindealController');
Route::resource('/flag','FlagController');
Route::resource('/front','FrontController');
Route::resource('/bid','BidController');
Route::resource('/assetbid','AssetBidController');
Route::resource('/livecomment','LivecommentController');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
  protected $table = 'products';
  protected $fillable= ['productName','productUnitPrice','productOwner'];
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Auth;
use \App\Product;
use Illuminate\Support\Facades\Input;
use \App\Media;
use \App\AssetCategory;
use File;
use Illuminate\Support\Facades\Redirect;

class ProductController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {
    if (Auth::User()) {
      if(Auth::User()->role == "Super"){
        $message= "Showing all data";
        $data= Product::all();
        return view('product.index', compact('data','message'));
      }
      if(Auth::User()->role == "Admin"){
        $data= Product::where('productOwner',Auth::id())->get();
        $message= "Showing all data";
        return View('product.index', compact('data','message'));
      }
      else{
        return redirect::to('/home');
      }
    }
    else{
      return View('auth.login');
    }
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
    if(Auth::User()){
      $message= "Form is ready to upload product";
      return View('product.create',compact('message'));
    }else{
      return View('auth.login');
    }

  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request)
  {

    if(Auth::User()){
      $data= new \App\Product;
      $data->productName = $request->get('productName');
      $data->productDescriptionPath = $request->get('productDescriptionPath');
      $data->productUnitPrice = $request->get('productUnitPrice');
      $data->productUnitDiscount = $request->get('productUnitDiscount');
      $data->productOwner = $request->get('productOwner');
      $data->productTotalPrice = $request->get('productTotalPrice');
      $data->productStatus = $request->get('productStatus');
      $data->productVisits = 0;
      $data->save();

      $categories = $request->get('categoryIds');
      foreach ($categories as $key => $value) {
        $productCategory = new \App\AssetCategory;
        $productCategory->categoryId = $value;
        $productCategory->productId = $data->id;
        $productCategory->save();
      }

      if($request->hasFile('files')){
        //$files=$request->file('files');
        $files=Input::file("files");
        $allowedImagefileExtension=['pdf','jpg','png','jpeg'];
        $destinationImages='product/images';
        $destinationVideo='product/videos';
        $allowedVideofileExtension=['mp4','flv','m4p','.mpg','.mpeg','.webm','.mov'];
        foreach ($files as $file) {
          $filename = time() . '-' .$file->getClientOriginalName();
          $extension = $file->getClientOriginalExtension();
          $checkImage=in_array($extension,$allowedImagefileExtension);
          $checkVideo=in_array($extension,$allowedVideofileExtension);
          if($checkImage){

            $file->move($destinationImages,$filename);
            $media=new Media();
            $media->mediaType="Image";
            $media->mediaExtension=$extension;
            $media->mediaPath=$filename;
            $media->mediasstatus="Active";
            $media->productId=$data->id;
            $media->save();

            // $data->productDescriptionPath=$destinationImages;
            // $data->save();
          }if($checkVideo){

            $file->move($destinationVideo,$filename);
            $media=new Media();
            $media->mediaType="Video";
            $media->mediaExtension=$extension;
            $media->mediaPath=$filename;
            $media->productId=$data->id;
            $media->save();

            // $data= Product::create($request->all());
            // $data->productDescriptionPath=$destinationImages;
            // $data->save();
          }else{
              $message="No data Saved; File Extension for Images 'pdf','jpg','png','jpeg'; for videos 'mp4','flv','m4p','.mpg','.mpeg','.webm','.mov' allowed ";
          }
        }
      }
      if(Auth::User()->role == "Super"){
        $data= Product::all();
      }
      else if(Auth::User()->role == "Admin"){
        $data= Product::where('productOwner',Auth::id())->get();
      }
      $message= "One Data Successfully saved";
      return View('product.index',compact('data','message'));
    }else{
      return View('auth.login');
    }
  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function show($id)
  {
      $data= \App\Product::findOrFail($id);
      $message = "One data Requested";
      $assetcategories = \App\AssetCategory::where('productId', $id)->get();
      foreach ($assetcategories as $key => $value) {
        if ($key==0) {
          $categories = \App\AssetCategory::where('categoryId',$value->categoryId)->get();
        }
        else{
          $result = \App\AssetCategory::where('categoryId',$value->categoryId)->get();
          $categories = $categories->merge($result);
        }
      }
      $count=0;
      $similarProducts=\App\AssetCategory::where('categoryId', $value->categoryId)->where('productId','!=',$id)->get();;
      foreach ($categories as $key => $value) {
        if ($value->productId!=$id) {
          $result = \App\AssetCategory::where('categoryId', $value->categoryId)->where('productId','!=',$id)->get();
          if ($count==0) {
            $similarProducts = $result;
            $count++;
          }
          else{
            $similarProducts = $similarProducts->merge($result);
          }
        }
      }

      $products = array();
      $productids = array();
      if (!$similarProducts->isEmpty()) {
        foreach ($similarProducts as $key => $value) {
          if (!in_array($value->productId, $productids)) {
            $productids[] = $value->productId;
            $products[] = \App\Product::findOrFail($value->productId);
          }
        }
      }
      return view('product.show',compact('data','message', 'products'));
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function edit($id)
  {
    if(Auth::User()){
    $data = Product::findOrFail($id);
    $media = Media::where('productId',$id)->get();
    $selectedCategories = \App\AssetCategory::where('productId', $id)->get();
    $message= "One data Requested";
    return view('product.edit', compact('data','message','media','selectedCategories'));
    }else{
      return View('auth.login');

    }
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, $id)
  {
    if(Auth::User()){
      $data = Product::findOrFail($id);
      //$input = Request::all();
      //$data->update($input);
      $data->productName = $request->get('productName');
      $data->productDescriptionPath = $request->get('productDescriptionPath');
      $data->productUnitPrice = $request->get('productUnitPrice');
      $data->productUnitDiscount = $request->get('productUnitDiscount');
      $data->productOwner = $request->get('productOwner');
      $data->productTotalPrice = $request->get('productTotalPrice');
      $data->productStatus = $request->get('productStatus');
      $data->save();

      $categories = $request->get('categoryIds');
      $productCategory = \App\AssetCategory::where('productId',$id)->get();
      foreach ($productCategory as $key => $value) {
        $value->delete();
      }

      foreach ($categories as $key => $value) {
        $productCategory = new \App\AssetCategory;
        $productCategory->categoryId = $value;
        $productCategory->productId = $data->id;
        $productCategory->save();
      }

      if($request->hasFile('files')){
        //$files=$request->file('files');
        $files=Input::file("files");
        $allowedImagefileExtension=['pdf','jpg','png','jpeg'];
        $destinationImages='product/images';
        $destinationVideo='product/videos';
        $allowedVideofileExtension=['mp4','flv','m4p','.mpg','.mpeg','.webm','.mov'];
        foreach ($files as $file) {
          $filename = time() . '-' .$file->getClientOriginalName();
          $extension = $file->getClientOriginalExtension();
          $checkImage=in_array($extension,$allowedImagefileExtension);
          $checkVideo=in_array($extension,$allowedVideofileExtension);
          if($checkImage){

            $file->move($destinationImages,$filename);
            $media=new Media();
            $media->mediaType="Image";
            $media->mediaExtension=$extension;
            $media->mediaPath=$filename;
            $media->mediasstatus="Active";
            $media->productId=$data->id;
            $media->save();

            // $data->productDescriptionPath=$destinationImages;
            // $data->save();
          }if($checkVideo){

            $file->move($destinationVideo,$filename);
            $media=new Media();
            $media->mediaType="Video";
            $media->mediaExtension=$extension;
            $media->mediaPath=$filename;
            $media->productId=$data->id;
            $media->save();

            // $data= Product::create($request->all());
            // $data->productDescriptionPath=$destinationImages;
            // $data->save();
          }else{
              $message="No data Saved; File Extension for Images 'pdf','jpg','png','jpeg'; for videos 'mp4','flv','m4p','.mpg','.mpeg','.webm','.mov' allowed ";
          }
        }
      }
      if(Auth::User()->role == "Super"){
        $data= Product::all();
      }
      else if(Auth::User()->role == "Admin"){
        $data= Product::where('productOwner',Auth::id())->get();
      }
      $message="One data updated";

resources/views/product/create.blade.php
@extends('layouts.dashboard')
@section('title','Dashboard')
@section('content')

<div class="content">
    <div class="container-fluid">
      <div class="row">
          <div class="content">
            <div class="col-md-12">
                <div class="card">
                    <div class="header">
                        <h4 class="title">Add New Product</h4>
                    </div>
                    <div class="content">
                        <form action="/products" method="POST" enctype="multipart/form-data">
                          {{ csrf_field() }}
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Product Title</label>
                                        <input type="text" class="form-control border-input" name="productName" placeholder="Enter Product Title" required/>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                  <div class="form-group">
                                      <label>Product Description</label>
                                      <textarea placeholder="Enter Product Description" class="form-control border-input" name="productDescriptionPath" cols="8" rows="8"></textarea>
                                  </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Product Unit Price (in Rupees)</label>
                                        <input type="number" class="form-control border-input" placeholder="Enter Product Unit Price" name="productUnitPrice" id="productUnitPrice" oninput="calculateDiscount()">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Product Unit Discount (in %)</label>
                                        <input type="number" name="productUnitDiscount" class="form-control border-input" placeholder="Product Unit Discount" value="0" id="productUnitDiscount" oninput="calculateDiscount()" max="100">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Product Discounted Price</label>
                                        <input type="number" name="productTotalPrice" class="form-control border-input" placeholder="Product Total Price" value="productTotalPrice" id="productTotalPrice" readonly>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Product Status</label>
                                        <select name="productStatus" class="form-control border-input">
                                          <option value="Active">Active</option>
                                          <option value="Deactive">Deactive</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Upload Images and Videos</label>
                                        <input accept=".jpg,.jpeg,.png,.mkv,.mp4" type="file" name="files[]" class="form-control border-input" multiple="true"/>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                  <div class="form-group">
                                      <label>Category</label>
                                      <?php $categories=\App\Category::all();?>
                                      <select class="form-control border-input" name="categoryIds[]" multiple>
                                        @<?php foreach ($categories as $key => $value): ?>
                                          <option value="{{$value->id}}">{{$value->categoryName}}</option>
                                        <?php endforeach; ?>
                                      </select>
                                  </div>
                                </div>
                                <input type="hidden" class="form-control border-input" name="productOwner" value="{{Auth::User()->id}}">

                            <div class="pull-right">
                                <button type="submit" class="btn btn-success btn-fill btn-wd">Add Product</button>
                            </div>
                            <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>
          </div>
        </div>
    </div>
    <script>
      function calculateDiscount(){
        var unitPrice = document.getElementById('productUnitPrice').value;
        var unitDiscount = document.getElementById('productUnitDiscount').value;
        var discountedPrice = unitPrice -  (unitPrice * (unitDiscount/100));
        document.getElementById('productTotalPrice').value = discountedPrice;
      }
    </script>
</div>
@endsection
@section('icon')
'ti-view-list-alt'
@endsection
@section('message')
"{{$message}}"
@endsection
@section('barcolor')
'success'
@endsection

resources/views/product/edit.blade.php
@extends('layouts.dashboard')
@section('title','Dashboard')
@section('content')

<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="content">
        <div class="col-md-12">
          <div class="card">
            <div class="header">
              <h4 class="title">Edit Product</h4>
            </div>
            <div class="content">
              <?php foreach ($media as $key => $value): ?>
              <div class="col-md-3">
                <?php if ($value->mediaType=='Image'): ?>
                  <img class="col-md-12" src="{{asset('product/images/').'/'.$value->mediaPath}}" alt="..."/>
                <?php else: ?>
                  <video class="col-md-12" controls>
  								  <source src="{{URL::asset('product/videos/').'/'.$value->mediaPath}}" type="video/mp4">
  								  Your browser does not support HTML5 video.
  								</video>
                <?php endif; ?>
                  <form action="{{ route('media.destroy', $value->id) }}" method="post" class="text-center">
                    <input type="text" hidden value="Product" name="type">
                    <input type="text" hidden value="{{$value->productId}}" name="otherid">
                    {{ method_field('DELETE') }}
                    {{ csrf_field() }}
                    <input type="submit" class="btn btn-danger" placeholder="Delete" value="Delete"/>
                  </form>
              </div>
              <?php endforeach; ?>
              <form action="/products/<?php echo $data->id;?>" method="POST" enctype="multipart/form-data">

                {{ csrf_field() }}
                {{method_field('PUT')}}
                  <div class="col-md-12">
                    <div class="form-group">
                      <label>Product Title</label>
                      <input value="{{$data->productName}}" type="text" class="form-control border-input" name="productName" placeholder="Enter Product Title" required/>
                    </div>
                  </div>


                  <div class="col-md-12">
                    <div class="form-group">
                      <label>Product Description</label>
                      <textarea class="form-control border-input" name="productDescriptionPath" cols="8" rows="8">{{$data->productDescriptionPath}}</textarea>
                    </div>
                  </div>


                  <div class="col-md-6">
                      <div class="form-group">
                          <label>Product Unit Price (in Rupees)</label>
                          <input value="{{$data->productUnitPrice}}" type="number" class="form-control border-input" placeholder="Enter Product Unit Price" name="productUnitPrice" id="productUnitPrice" oninput="calculateDiscount()">
                      </div>
                  </div>
                  <div class="col-md-6">
                      <div class="form-group">
                          <label>Product Unit Discount (in %)</label>
                          <input value="{{$data->productUnitDiscount}}" type="number" name="productUnitDiscount" class="form-control border-input" placeholder="Product Unit Discount" value="productUnitDiscount" id="productUnitDiscount" oninput="calculateDiscount()" max="100">
                      </div>
                  </div>


                  <div class="col-md-6">
                      <div class="form-group">
                          <label>Product Total Price</label>
                          <input readonly value="{{$data->productTotalPrice}}" type="number" name="productTotalPrice" class="form-control border-input" placeholder="Product Total Price" id="productTotalPrice">
                      </div>
                  </div>
                  <div class="col-md-6">
                      <div class="form-group">
                          <label>Product Status</label>
                          <select name="productStatus" class="form-control border-input">
                            @if($data->productStatus=='Active')
                            <option value="Active" selected>Active</option>
                            <option value="Deactive">Deactive</option>
                            @else
                            <option value="Active">Active</option>
                            <option value="Deactive" selected>Deactive</option>
                            @endif
                          </select>
                      </div>
                  </div>


                  <div class="col-md-12">
                    <div class="form-group">
                      <label>Upload Images and Videos</label>
                      <input accept=".jpg,.jpeg,.png,.mkv,.mp4" type="file" name="files[]" class="form-control border-input" multiple="true"/>
                    </div>
                  </div>
                  <div class="col-md-12">
                    <div class="form-group">
                        <label>Category</label>
                        <?php $categories=\App\Category::all();?>
                        <select class="form-control border-input" name="categoryIds[]" multiple>

                          @<?php foreach ($categories as $key => $value): ?>
                            <?php $selected = false; ?>
                            <?php foreach ($selectedCategories as $key => $value1): ?>
                              @if($value1->categoryId==$value->id)
                              <?php $selected = true; ?>
                              <option value="{{$value->id}}" selected>{{$value->categoryName}}</option>
                              @endif
                            <?php endforeach; ?>
                            @if(!$selected)
                            <option value="{{$value->id}}">{{$value->categoryName}}</option>
                            @endif
                          <?php endforeach; ?>
                        </select>
                    </div>
                  </div>
                <div class="text-right col-md-12">
                  <button type="submit" class="btn btn-info btn-fill btn-wd">Update Product</button>
                </div>
                <div class="clearfix"></div>
                <input type="hidden" class="form-control border-input" name="productOwner" value="{{Auth::User()->id}}">
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script>
    function calculateDiscount(){
      var unitPrice = document.getElementById('productUnitPrice').value;
      var unitDiscount = document.getElementById('productUnitDiscount').value;
      var discountedPrice = unitPrice -  (unitPrice * (unitDiscount/100));
      document.getElementById('productTotalPrice').value = discountedPrice;
    }
  </script>
</div>
@endsection

resources/views/product/index.blade.php
@extends('layouts.dashboard')
@section('title','Dashboard')
@section('content')
<div class="content">
    <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
              <div class="card">
                  <div class="header">
                      <h4 class="title">All @if($message=='Favourites' || $message=='Flaged') {{$message}} @endif Products</h4>
                      <p class="category">Records regarding Product table</p>
                      @if($message != 'Flaged' && $message !='Favourites')
                      <div class="pull-right">
                          <a class="btn btn-primary" href="{{URL::asset('products/create')}}">Add New</a>
                      </div>
                      @endif
                  </div>
                  <div class="content table-responsive table-full-width">
                      <table class="table table-striped">
                          <thead>
                            <th>Product Primary Image</th>
                            <th>Product Title</th>
                            <th>Product Uploader</th>
                            <th>Product Status</th>
                            <th>Visits</th>
                            <th>Actions</th>
                          </thead>
                          <tbody>
                            @foreach($data as $info)
                              <tr>
                                <?php
                                $profileImage=\App\Media::where('productId',$info->id)->where('mediaType', 'Image')->first();
                                ?>
                                @if(!empty($profileImage))
                                <td><img src="{{asset('product/images/').'/'.$profileImage->mediaPath}}" width="75px" height="auto"/></td>
                                @else
                                <td><i class="ti-view-list-alt"></i></td>
                                @endif
                                <td>{{$info->productName}}</td>
                                <?php $userProfileId= \App\User::findOrFail($info->productOwner);
                                  //$userProfileImage= \App\Media::findOrFail($userProfileId->id);
                                ?>
                                <td><a href="/users/<?php echo $userProfileId->id;?>">{{$userProfileId->name}}</a></td>
                                <td>{{$info->productStatus}}</td>
                                <td>{{$info->productVisits}}</td>
                                <td>
                                  <a class="btn btn-warning" href="/products/<?php echo $info->id;?>/edit">Edit</a>
                                  <a href="/products/<?php echo $info->id; ?>" class="btn btn-success">View</a>
                                  <form action="{{ route('products.destroy', $info->id) }}" method="post" style="display:inline">
                                  {{ method_field('DELETE') }}
                                  {{ csrf_field() }}
                                    <input type="submit" class="btn btn-danger" placeholder="Delete" value="Delete"/>
                                  </form>&nbsp
                                </td>
                              </tr>
                            @endforeach
                          </tbody>
                      </table>
                  </div>
              </div>
          </div>
        </div>
    </div>
</div>

@endsection
@section('icon')
'ti-user'
@endsection
@section('message')
"<?php echo $message;?>"
@endsection
@section('barcolor')
'success'
@endsection