routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/websiteDeals', 'HomeController@websitedeal');
Route::get('/deal/{category}/{id}', 'DealController@dealsInCategory');
Route::get('/product/{category}/{id}', 'ProductController@productsInCategory');
Auth::routes();
Route::get('/logout', function(){
    if (Auth::user()) {
     Auth::logout();
     return view('welcome');
  }
});
Route::get('/dashboard','HomeController@dashboard');
Route::get('/home', 'HomeController@index');
Route::get('/cart', 'HomeController@cart');
Route::get('/contact', 'FrontController@contact');
Route::post('/sendMail', 'FrontController@sendMail');
Route::post('/order/address-contact', 'OrdermetaController@addressescontacts');
Route::get('/favourite/{type}','FavouriteController@favourites');
Route::get('/reviewandrating/{id}/{type}','ReviewandratingController@reviewrate');
Route::get('/flaged/{type}','FlagController@flaged');
Route::get('/websiteBids','BidController@websiteBids');
Route::get('/user/{id}/statusNeedChange','UserController@statusNeedChange');
Route::get('/getBids/{assetbid_id}', 'BidController@getBids');
Route::get('/assetbid/viewDetails/{assetbid_id}', 'BidController@getBidsOfAsset');
Route::post('/addMapLink', 'UserController@addMapLink');
Route::post('/deleteGoogleMapsLink', 'UserController@deleteGoogleMapsLink');
Route::resource('/users', 'UserController');
Route::resource('/addresses','AddressController');
Route::resource('/category','CategoryController');
Route::resource('/contacts','ContactController');
Route::resource('/deals','DealController');
Route::resource('/favourite','FavouriteController');
Route::resource('/media','MediaController');
Route::resource('/message','MessageController');
Route::resource('/messagemedia','MessagemediaController');
Route::resource('/order','OrdermetaController');
Route::resource('/products','ProductController');
Route::resource('/reviewandrating','ReviewandratingController');
Route::resource('/subcategory','SubcategoryController');
Route::resource('/support','SupportController');
Route::resource('/supportmedia','SupportmediaController');
Route::resource('/productindeals','ProductindealController');
Route::resource('/flag','FlagController');
Route::resource('/front','FrontController');
Route::resource('/bid','BidController');
Route::resource('/assetbid','AssetBidController');
Route::resource('/livecomment','LivecommentController');

app/Subcategory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Subcategory extends Model
{
  protected $table = 'subcategories';

}

app/Http/Controllers/SubcategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Auth;
Use \App\Subcategory;

class SubcategoryController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {
    $authenticatedUser=Auth::User();
    $message= "Showing all data";
      if($authenticatedUser->role == 'Super'){
        $data= Subcategory::all();
        return view('subcategory.index', compact('data','message'));
      }if($authenticatedUser->role != 'Super'){
        $data= Subcategory::where('subcategoryesOfUser','=',$authenticatedUser->id);
        return View('subcategory.index', compact('data','message'));
      }else{
        return View('auth.login');
      }
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
    if(Auth::User()){
      return View('subcategory.create');
    }else{
      return View('auth.login');
    }

  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request)
  {
    if(Auth::User()){
      //$data= Request::all();
      //$data= Subcategory::create($data);
      $subcategory = new \App\Subcategory;
      $subcategory->childCategory = $request->get('childCategory');
      $subcategory->parentCategory = $request->get('parentCategory');
      $subcategory->categorystatus = $request->get('categorystatus');
      $subcategory->save();
      $data= Subcategory::all();
      $message= "One Data Successfully saved";
      return View('subcategory.index',compact('data','message'));
    }else{
      return View('auth.login');
    }
  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function show($id)
  {
    if(Auth::User()){
      $data= Subcategory::findOrFail($id);
      $message= "One data Requested";
      return view('subcategory.show',compact('date','message'));
    }else{
      return View('auth.login');
    }
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function edit($id)
  {
    if(Auth::User()){
    $data = Subcategory::findOrFail($id);
    $message= "One data Requested";
    return view('subcategory.edit', compact('data','message'));
    }else{
      return View('auth.login');

    }
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, $id)
  {
    if(Auth::User()){
    $data = Subcategory::findOrFail($id);
    //$input = Request::all();
    $data->childCategory = $request->get('childCategory');
    $data->parentCategory = $request->get('parentCategory');
    $data->categorystatus = $request->get('categorystatus');
    $data->save();
    $data= Subcategory::all();
    //$data->update($input);
    $message="One data updated";
    return View('subcategory.index',compact('data','message'));
    }else{
      return View('auth.login');
    }
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function destroy($id)
  {
    if(Auth::User()){
    $data = Subcategory::findOrFail($id);
    $data->delete();
    $message="One data deleted";
    $data= Subcategory::all();
    return View('subcategory.index',compact('data','message'));
    }else{
      return View('auth.login');
    }
  }
}

resources/views/Subcategory/create.blade.php
@extends('layouts.dashboard')
@section('title','Dashboard')
@section('content')

<div class="content">
    <div class="container-fluid">
      <div class="row">
          <div class="content">
            <div class="col-md-12">
                <div class="card">
                    <div class="header">
                        <h4 class="title">Add New Sub Category</h4>
                    </div>
                    <div class="content">
                        <form action="/subcategory" method="POST" enctype="multipart/form-data">
                          {{ csrf_field() }}
                          <?php $categories=\App\Category::where('categorystatus', 'Active')->get(); ?>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Parent Category</label>
                                        <select class="form-control border-input" name="parentCategory">
                                          <?php foreach ($categories as $key => $value): ?>
                                            <option value="{{$value->id}}">{{$value->categoryName}}</option>
                                          <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Child Category</label>

                                        <select class="form-control border-input" name="childCategory">
                                          <?php foreach ($categories as $key => $value): ?>
                                            <option value="{{$value->id}}">{{$value->categoryName}}</option>
                                          <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Sub Category Status</label>
                                        <select class="form-control border-input" name="categorystatus">
                                          <option value="Active">Active</option>
                                          <option value="Deactive">Deactive</option>
                                        </select>
                                    </div>
                                </div>
                            <div class="pull-right">
                                <button type="submit" class="btn btn-success btn-fill btn-wd">Add Sub Category</button>
                            </div>
                            <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>
          </div>
        </div>
    </div>
</div>
@endsection

resources/views/Subcategory/edit.blade.php
@extends('layouts.dashboard')
@section('title','Dashboard')
@section('content')

<div class="content">
    <div class="container-fluid">
      <div class="row">
          <div class="content">
            <div class="col-lg-12 col-md-12">
                <div class="card">
                    <div class="header">
                        <h4 class="title">Edit Subcategory</h4>
                    </div>
                    <div class="content">
                        <form action="/subcategory/<?php echo $data->id;?>" method="POST" enctype="multipart/form-data">
                          {{method_field('PUT')}}
                          {{ csrf_field() }}
                          <?php $categories=\App\Category::where('categorystatus', 'Active')->get(); ?>
                            <div class="row">
                              <div class="col-md-6">
                                <div class="form-group">
                                    <label>Parent Category</label>
                                    <select class="form-control border-input" name="parentCategory">
                                      @<?php foreach ($categories as $key => $value): ?>
                                        @if($data->parentCategory==$value->id)
                                        <option value="{{$value->id}}" selected>{{$value->categoryName}}</option>
                                        @else
                                        <option value="{{$value->id}}">{{$value->categoryName}}</option>
                                        @endif
                                      <?php endforeach; ?>
                                    </select>
                                </div>
                              </div>
                              <div class="col-md-6">
                                <div class="form-group">
                                    <label>Child Category</label>

                                    <select class="form-control border-input" name="childCategory">
                                      @<?php foreach ($categories as $key => $value): ?>
                                        @if($data->childCategory==$value->id)
                                        <option value="{{$value->id}}" selected>{{$value->categoryName}}</option>
                                        @else
                                        <option value="{{$value->id}}">{{$value->categoryName}}</option>
                                        @endif
                                      <?php endforeach; ?>
                                    </select>
                                </div>

                              </div>
                            </div>
                            <div class="row">
                              <div class="col-md-12">
                                  <div class="form-group">
                                      <label>Sub Category Status</label>
                                      <select class="form-control border-input" name="categorystatus">
                                        @if($data->categorystatus=='Active')
                                        <option value="Active" selected>Active</option>
                                        <option value="Deactive">Deactive</option>
                                        @else
                                        <option value="Active">Active</option>
                                        <option value="Deactive" selected>Deactive</option>
                                        @endif
                                      </select>
                                  </div>
                              </div>
                            </div>
                            <div class="pull-right">
                                <button type="submit" class="btn btn-success btn-fill btn-wd">Update Sub Category</button>
                            </div>
                            <div class="clearfix"></div>
                        </form>
                      </div>
                </div>
            </div>
          </div>
        </div>
    </div>
</div>
@endsection

resources/views/Subcategory/index.blade.php
@extends('layouts.dashboard')
@section('title','Dashboard')
@section('content')
<div class="content">
    <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
              <div class="card">
                  <div class="header">
                      <h4 class="title">All Sub Categories</h4>
                      <p class="category">Records regarding Sub Category table</p>
                      <div class="pull-right">
                          <a class="btn btn-primary" href="{{URL::asset('subcategory/create')}}">Add New</a>
                      </div>
                  </div>
                  <div class="content table-responsive table-full-width">
                      <table class="table table-striped">
                          <thead>
                            <th>ID</th>
                            <th>Parent Category</th>
                            <th>Child Category</th>
                            <th>Status</th>
                            <th>Actions</th>
                          </thead>
                          <tbody>
                            @foreach($data as $info)
                              <?php
                                $child=\App\Category::where('id',$info->childCategory)->first();
                                $parent=\App\Category::where('id',$info->parentCategory)->first();
                              ?>
                              <tr>
                                <td>{{$info->id}}</td>
                                <td>{{$parent->categoryName}}</td>
                                <td>{{$child->categoryName}}</td>
                                <td>{{$info->categorystatus}}</td>

                                <td><a class="btn btn-warning" href="/subcategory/<?php echo $info->id;?>/edit">Edit</a> <form action="{{ route('subcategory.destroy', $info->id) }}" method="post" style="display:inline">
                                  {{ method_field('DELETE') }}
                                  {{ csrf_field() }}
                                  <input type="submit" class="btn btn-danger" placeholder="Delete" value="Delete"/>
                                </form>&nbsp</td>
                              </tr>
                            @endforeach
                          </tbody>
                      </table>

                  </div>
              </div>
          </div>

        </div>
    </div>
</div>
@endsection
@section('icon')
'ti-user'
@endsection
@section('message')
"<?php echo $message;?>"
@endsection
@section('barcolor')
'success'
@endsection