routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/websiteDeals', 'HomeController@websitedeal');
Route::get('/deal/{category}/{id}', 'DealController@dealsInCategory');
Route::get('/product/{category}/{id}', 'ProductController@productsInCategory');
Auth::routes();
Route::get('/logout', function(){
    if (Auth::user()) {
     Auth::logout();
     return view('welcome');
  }
});
Route::get('/dashboard','HomeController@dashboard');
Route::get('/home', 'HomeController@index');
Route::get('/cart', 'HomeController@cart');
Route::get('/contact', 'FrontController@contact');
Route::post('/sendMail', 'FrontController@sendMail');
Route::post('/order/address-contact', 'OrdermetaController@addressescontacts');
Route::get('/favourite/{type}','FavouriteController@favourites');
Route::get('/reviewandrating/{id}/{type}','ReviewandratingController@reviewrate');
Route::get('/flaged/{type}','FlagController@flaged');
Route::get('/websiteBids','BidController@websiteBids');
Route::get('/user/{id}/statusNeedChange','UserController@statusNeedChange');
Route::get('/getBids/{assetbid_id}', 'BidController@getBids');
Route::get('/assetbid/viewDetails/{assetbid_id}', 'BidController@getBidsOfAsset');
Route::post('/addMapLink', 'UserController@addMapLink');
Route::post('/deleteGoogleMapsLink', 'UserController@deleteGoogleMapsLink');
Route::resource('/users', 'UserController');
Route::resource('/addresses','AddressController');
Route::resource('/category','CategoryController');
Route::resource('/contacts','ContactController');
Route::resource('/deals','DealController');
Route::resource('/favourite','FavouriteController');
Route::resource('/media','MediaController');
Route::resource('/message','MessageController');
Route::resource('/messagemedia','MessagemediaController');
Route::resource('/order','OrdermetaController');
Route::resource('/products','ProductController');
Route::resource('/reviewandrating','ReviewandratingController');
Route::resource('/subcategory','SubcategoryController');
Route::resource('/support','SupportController');
Route::resource('/supportmedia','SupportmediaController');
Route::resource('/productindeals','ProductindealController');
Route::resource('/flag','FlagController');
Route::resource('/front','FrontController');
Route::resource('/bid','BidController');
Route::resource('/assetbid','AssetBidController');
Route::resource('/livecomment','LivecommentController');

app/Bid.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Bid extends Model
{
    protected $table = 'bids';

}

app/Http/Controllers/BidController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Auth;
use Carbon\Carbon;
use Illuminate\Support\Facades\Redirect;

class BidController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      return view('bid.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('bid.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $checkBids = \App\Bid::where('bidAmount', $request->get('bidAmount'))->where('assetsBidId', $request->get('assetBidId'))->get();
      if($checkBids->isEmpty()){
        $bid = new \App\Bid;
        $bid->bidAmount = $request->get('bidAmount');
        $bid->assetsBidId = $request->get('assetBidId');
        $bid->byUserId = Auth::id();
        $bid->status = "run";
        $bid->save();
        $url = "/assetbid/".$request->get('assetBidId');
        return redirect::to($url);
      }
      else{
        $message = "This amount has already been bid";
        $url = "/assetbid/".$request->get('assetBidId');
        return redirect::to($url);
      }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $assetbid = \App\AssetBid::findOrFail($id);
      $data= \App\Product::findOrFail($assetbid->productId);
      $productId = $data->id;
      $message= "One data Requested";
      $assetcategories = \App\AssetCategory::where('productId', $productId)->get();
      foreach ($assetcategories as $key => $value) {
        if ($key==0) {
          $categories = \App\AssetCategory::where('categoryId',$value->categoryId)->get();
        }
        else{
          $result = \App\AssetCategory::where('categoryId',$value->categoryId)->get();
          $categories = $categories->merge($result);
        }
      }
      $count=0;
      $similarProducts=\App\AssetCategory::where('categoryId', $value->categoryId)->where('productId','!=',$productId)->get();;
      foreach ($categories as $key => $value) {
        if ($value->productId!=$productId) {
          $result = \App\AssetCategory::where('categoryId', $value->categoryId)->where('productId','!=',$productId)->get();
          if ($count==0) {
            $similarProducts = $result;
            $count++;
          }
          else{
            $similarProducts = $similarProducts->merge($result);
          }
        }
      }

      $products = array();
      $productids = array();
      if (!$similarProducts->isEmpty()) {
        foreach ($similarProducts as $key => $value) {
          if (!in_array($value->productId, $productids)) {
            $productids[] = $value->productId;
            $products[] = \App\Product::findOrFail($value->productId);
          }
        }
      }
      return view('bid.show',compact('data','message', 'products', 'assetbid'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $bid = \App\Bid::findOrFail($id);
        $bid->delete();
        return redirect::to('/bid');
    }

    public function websiteBids(){
      $now = new Carbon();
      $data = \App\AssetBid::where('status', 'run')->get();
      return view('websiteBids', compact('now', 'data'));
    }

    public function getBids($assetbid_id){
      $bids = \App\Bid::where('assetsBidId', $assetbid_id)->get();
      $comments = \App\Livecomment::where('assetBidId', $assetbid_id)->get();
      $userCommented = [];
      $users = [];

      foreach ($bids as $key => $value) {
        $users[] = \App\User::findOrFail($value->byUserId);
      }

      foreach ($comments as $key => $value) {
        $userCommented[] = \App\User::findOrFail($value->byUserId);
      }
      $assetbid = \App\AssetBid::findOrFail($assetbid_id);
      $now = new Carbon();
      $endTime = new Carbon($assetbid->endTime);
      $remain = $now->diff($endTime);
      $remainTime = $remain->format('%h:%i:%s');
      $expireCheck = false;
      if ($now > $assetbid->endTime) {
        $expireCheck = true;
        $count = $bids->count();
        if($count == 0){
            $assetbid->status = "loss";
            $assetbid->save();
        }
        else{
            $highestBid = \App\Bid::where('assetsBidId', $assetbid_id)->orderBy('bidAmount', 'desc')->first();
            $highestBid->status = "win";
            $highestBid->save();
            $assetbid->status = "win";
            $assetbid->save();
        }
      }
      $iframe = Auth::User()->googleMapsLink;
      return response()->json([
        'bids' => $bids,
        'users' => $users,
        'isExpire' => $expireCheck,
        'remaining' => $remainTime,
        'comments' => $comments,
        'userCommented' => $userCommented,
        'iframe' => $iframe,
      ]);
    }

    public function getBidsOfAsset($assetbid_id){
      return view('assetbid.details', compact('assetbid_id'));
    }
}

resources/views/bid/create.blade.php
@extends('layouts.dashboard')
@section('title','Dashboard')
@section('content')

<div class="content">
    <div class="container-fluid">
      <div class="row">
          <div class="content">
            <div class="col-md-12">
                <div class="card">
                    <div class="header">
                        <h4 class="title">Add New Bid</h4>
                    </div>
                    <div class="content">
                        <form action="/bid" method="POST" enctype="multipart/form-data">
                          {{ csrf_field() }}
                          <div class="col-md-6">
                              <div class="form-group">
                                  <label>Product</label>
                                  <?php $products=\App\Product::where('productStatus', 'Active')->get();?>
                                  <select class="form-control border-input" required name="productId">
                                    <option value="null">Select Product</option>
                                    @<?php foreach ($products as $key => $value): ?>
                                      <option value="{{$value->id}}">{{$value->productName}}</option>
                                    <?php endforeach; ?>
                                  </select>
                              </div>
                          </div>
                          <div class="col-md-6">
                              <div class="form-group">
                                  <label>Deals</label>
                                  <?php $deals=\App\Deal::where('dealStatus', 'Active')->get();?>
                                  <select class="form-control border-input" required name="dealId">
                                    <option value="null">Select Deal</option>
                                    @<?php foreach ($deals as $key => $value): ?>
                                      <option value="{{$value->id}}">{{$value->dealName}}</option>
                                    <?php endforeach; ?>
                                  </select>
                              </div>
                          </div>
                          <div class="col-md-6">
                              <div class="form-group">
                                  <label>Base Amount</label>
                                  <input type="number" class="form-control border-input" placeholder="Enter Base Amount" name="baseAmount" required min="1">
                              </div>
                          </div>
                          <div class="col-md-6">
                              <div class="form-group">
                                  <label>Time</label>
                                  <input type="number" name="time" class="form-control border-input" placeholder="Enter Time" required min="1">
                              </div>
                          </div>
                          <input type="hidden" class="form-control border-input" name="sellerId" value="{{Auth::User()->id}}">
                          <div class="col-md-12">
                              <button type="submit" class="btn btn-success btn-fill btn-wd pull-right">Add Bid</button>
                          </div>
                          <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>
          </div>
        </div>
    </div>
</div>
@endsection

resources/views/bid/index.blade.php
@extends('layouts.dashboard')
@section('title','Dashboard')
@section('content')
<div class="content">
    <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
              <div class="card">
                  <div class="header">
                      <h4 class="title">All Bids</h4>
                      <?php $message = "All Bids" ?>
                      <p class="category">Records regarding Bids table</p>

                      <div class="pull-right">
                          <a class="btn btn-primary" href="{{URL::asset('bid/create')}}">Add New</a>
                      </div>
                      <?php
                      if(Auth::User()->role=="Super"){
                        $data = \App\AssetBid::all();
                      }
                      else if(Auth::User()->role=="admin"){
                        $data = \App\AssetBid::where('sellerId', Auth::id())->get();
                      }
                      else if(Auth::User()->role=="client"){

                      }
                      else{

                      }
                      ?>
                  </div>
                  <div class="content table-responsive table-full-width">
                      <table class="table table-striped">
                          <thead>
                            <th>Bid Id</th>
                            <th>Bid Asset</th>
                            <th>Bid Uploader</th>
                            <th>Bid Status</th>
                            <th>Actions</th>
                          </thead>
                          <tbody>
                            @foreach($data as $info)
                              <tr>
                                <td>{{$info->id}}</td>
                                @if($info->dealId)
                                <?php $deal = \App\Deal::findOrFail($info->dealId); ?>
                                <td>{{$deal->dealName}}</td>
                                @elseif($info->productId)
                                <?php $product = \App\Product::findOrFail($info->productId); ?>
                                <td>{{$product->productName}}</td>
                                @endif
                                <?php $uploader = \App\User::findOrFail($info->sellerId); ?>
                                <td>{{$uploader->name}}</td>
                                <td>{{$info->status}}</td>
                                <td>
                                  <a href="/bid/<?php echo $info->id; ?>" class="btn btn-success">View</a>
                                  <form action="{{ route('bid.destroy', $info->id) }}" method="post" style="display:inline">
                                  {{ method_field('DELETE') }}
                                  {{ csrf_field() }}
                                    <input type="submit" class="btn btn-danger" placeholder="Delete" value="Delete"/>
                                  </form>&nbsp
                                </td>
                              </tr>
                            @endforeach
                          </tbody>
                      </table>
                  </div>
              </div>
          </div>
        </div>
    </div>
</div>
@endsection
@section('icon')
'ti-user'
@endsection
@section('message')
"<?php echo $message;?>"
@endsection
@section('barcolor')
'success'
@endsection

resources/views/bid/show.blade.php
@extends('layouts.app')
@section('title','Single')
@section('content')
  <!-- banner-bootom-w3-agileits -->
<div class="banner-bootom-w3-agileits" id="app">
	<div class="container">
		<div class="col-md-12 text-center showProductCategories">
			<?php
			$assetcategories = \App\AssetCategory::where('productId', $data->id)->get();
			$categoryids = array();
			foreach ($assetcategories as $key => $value) {
				if (!in_array($value->categoryId, $categoryids)) {
					$categories[] = \App\Category::where('id', $value->categoryId)->first();
					$categoryids[] = $value->categoryId;
				}
			}
			?>

			@if(!empty($categories))
			<div>
			<?php foreach ($categories as $key => $value): ?>
				<small><a href="/product/<?php echo "$value->categoryName/"; echo "$value->id"; ?>" style="display:inline; background-color:#348e37; padding:1%; margin-right:1%; color:white">{{$value->categoryName}}</a></small><?php if (sizeof($categories)-1>$key): ?>

				<?php endif; ?>
			<?php endforeach; ?>
		</div>
			@endif
		</div>
	   <div class="col-md-4 single-right-left ">
			<div class="grid images_3_of_2">
				<div class="flexslider">
					<ul class="slides">
            <?php
						$productImages=\App\Media::where('productId',$data->id)->where('mediaType', 'Image')->get();
						$productVideos=\App\Media::where('productId',$data->id)->where('mediaType', 'Video')->get();
						?>
            <?php foreach ($productImages as $key => $value): ?>
              <li data-thumb="{{URL::asset('product/images/').'/'.$value->mediaPath}}">
  							<div class="thumb-image"> <img src="{{URL::asset('product/images/').'/'.$value->mediaPath}}" data-imagezoom="true" class="img-responsive"> </div>
  						</li>
            <?php endforeach; ?>
					</ul>
					<div class="clearfix"></div>
				</div>
			</div>
		</div>
		<div class="col-md-8 single-right-left simpleCart_shelfItem">
			<?php
			$data->productVisits = $data->productVisits + 1;
			$data->save();
			?>
					<h3>{{$data->productName}}
						<?php
						$checkFavourite = \App\Favourite::where('byUserId', Auth::id())->where('toProductId', $data->id)->first();
						?>
						@if(!empty($checkFavourite))
						<form action="{{ route('favourite.destroy', $checkFavourite->id) }}" method="post" style="display:inline">
							{{ method_field('DELETE') }}
							{{ csrf_field() }}
							<input type="text" value="{{$data->id}}" name="productId" hidden>
							<input type="text" value="Product" name="type" hidden>
							<button style="border:none; background-color:white" class="favLinkChecked" type="submit"><i class="fas fa-heart" title="Remove From Favourite"></i></button>
						</form>
						@else
						<form action="/favourite" method="post" style="display:inline">
              {{ csrf_field() }}
              <input type="text" value="{{Auth::id()}}" name="byUserId" hidden>
              <input type="text" value="{{$data->id}}" name="toProductId" hidden>
              <input type="text" value="Product" name="type" hidden>
              <button style="border:none ; background-color:white" class="favLink" type="sumbit"><i class="fas fa-heart" title="Favourite"></i></button>
            </form>
						@endif

						<?php
						$checkFlag = \App\Flag::where('byUserId', Auth::id())->where('toProductId', $data->id)->first();
						?>
						@if(!empty($checkFlag))
						<form action="{{ route('flag.destroy', $checkFlag->id) }}" method="post" style="display:inline">
							{{ method_field('DELETE') }}
							{{ csrf_field() }}
							<input type="text" value="{{$data->id}}" name="productId" hidden>
							<input type="text" value="Product" name="type" hidden>
							<button style="border:none; background-color:white" class="flagLinkChecked" type="submit"><i class="fas fa-flag" title="Remove From Flag"></i></button>
						</form>
						@else
						<form action="/flag" method="post" style="display:inline">
              {{ csrf_field() }}
              <input type="text" value="{{Auth::id()}}" name="byUserId" hidden>
              <input type="text" value="{{$data->id}}" name="toProductId" hidden>
            	<input type="text" value="Product" name="type" hidden>
              <button style="border:none ; background-color:white" class="flagLink" type="submit"><i class="fas fa-flag" title="Flag"></i></button>
            </form>
						@endif
            <div class="pull-right">
							<input type="number" placeholder="Bid Amount">
							<?php
							$bids = \App\Bid::where('assetsBidId', $assetbid->id)->get();
							foreach ($bids as $key => $value) {
								echo '<p>$value->bidAmount</p>';
							}
							?>
						</div>
												</h3>
												<?php
												$rates = \App\Reviewandrating::where('toProductId', $data->id)->get();
												if (!$rates->isEmpty()) {
													$count = \App\Reviewandrating::where('toProductId', $data->id)->count();
													$stars = 0;
													foreach ($rates as $key => $value) {
														$stars = $stars + $value->stars;
													}
													$avg = $stars / $count;
													$fullStars = $avg*10;
													$halfStar = 0;
													if ($fullStars%10 > 0) {
													 $halfStar = 1;
													}
													$fullStars = floor($avg);
													$starCount = $fullStars + $halfStar;
													$remain = 5 - $starCount;
													for ($i=0; $i < $fullStars; $i++) {
														echo '<i class="fas fa-star starChecked"></i>';
													}
													for ($i=0; $i < $halfStar; $i++) {
														echo '<i class="fas fa-star-half-alt starChecked"></i>';
													}
													for ($i=0; $i < $remain; $i++) {
														echo '<i class="fas fa-star starUnchecked"></i>';
													}
													echo " <small>($count Reviews)</small>";
												}
												?>
					<div class="description">
						<div class="color-quality-right">
							<h5>Description:</h5>
							{{$data->productDescriptionPath}}
							<?php foreach ($productVideos as $key => $value): ?>
								<br><br>
								<video class="col-md-12" controls>
								  <source src="{{URL::asset('product/videos/').'/'.$value->mediaPath}}" type="video/mp4">
								  Your browser does not support HTML5 video.
								</video>
							<?php endforeach; ?>
						</div>
					</div>
		     </div>
	 			<div class="clearfix"> </div>
				<!-- /new_arrivals -->
	<div class="responsive_tabs_agileits">
				<div id="horizontalTab">
						<ul class="resp-tabs-list">
							<li>Reviews</li>
						</ul>
					<div class="resp-tabs-container">
						<div class="tab2">

							<div class="single_page_agile_its_w3ls">
								<div class="bootstrap-tab-text-grids">
									@if($message=='Rate')
									<div class="bootstrap-tab-text-grid">
										<div class="add-review">
	 										<h4>add a review</h4>
	 										<form action="/reviewandrating" method="POST" enctype="multipart/form-data">
												{{ csrf_field() }}
	 											<input type="text" value="{{$data->id}}" hidden name="toProductId">
	 											<div class="rating1">
	 												<fieldset class="starability-basic" style="min-height:auto;">
	 												  <input type="radio" id="no-rate" class="input-no-rate" name="rating" value="0" checked aria-label="No rating." />
	 												  <input type="radio" id="first-rate1" name="rating" value="1" />
	 												  <label for="first-rate1" title="Terrible">1 star</label>
	 												  <input type="radio" id="first-rate2" name="rating" value="2" />
	 												  <label for="first-rate2" title="Not good">2 stars</label>
	 												  <input type="radio" id="first-rate3" name="rating" value="3" />
	 												  <label for="first-rate3" title="Average">3 stars</label>
	 												  <input type="radio" id="first-rate4" name="rating" value="4" />
	 												  <label for="first-rate4" title="Very good">4 stars</label>
	 												  <input type="radio" id="first-rate5" name="rating" value="5" />
	 												  <label for="first-rate5" title="Amazing">5 stars</label>
	 												</fieldset>
	 											</div>
												<input type="text" value="Product" name="type" hidden>
	 											<textarea name="review" placeholder="Review"></textarea>
	 											<input type="submit" value="SEND">
	 										</form>
	 									</div>
									</div>
									@endif
									<?php
									$reviews = \App\Reviewandrating::where('toProductId', $data->id)->get();
									?>
									<?php foreach ($reviews as $key => $value): ?>
									<?php $userImage=\App\Media::where('userProfileId',$value->byUserId)->first(); ?>

									<div class="bootstrap-tab-text-grid">
										<?php if ($userImage): ?>
											<div class="bootstrap-tab-text-grid-left">
												<img src="{{URL::asset('profile/images/').'/'.$userImage->mediaPath}}" alt=" " class="img-responsive">
											</div>
										<?php else: ?>
											<div class="bootstrap-tab-text-grid-left">
												<i class="fas fa-user"></i>
											</div>
										<?php endif; ?>
											<div class="bootstrap-tab-text-grid-right">
												<ul>
													<?php
													$user = \App\User::where('id', $value->byUserId)->first();
													?>
													<li>
														@if(Auth::User()->role=='Super')
														<a href="/users/<?php echo $user->id;?>">{{$user->name}}</a>
														@else
														{{$user->name}}
														@endif
													</li>
													<li>
														<?php
														for ($i=0; $i < $value->stars; $i++) {
															echo '<i class="fas fa-star starChecked"></i>';
														}
														$remain = 5 - $value->stars;
														for ($i=0; $i < $remain; $i++) {
															echo '<i class="fas fa-star starUnchecked"></i>';
														}
														?>
													</li>
												</ul>
												<p>{{$value->reviewPath}}</p>
											</div>

										<div class="clearfix"> </div>
						       </div>
									 <?php endforeach; ?>
								 </div>
							 </div>
						 </div>
					</div>
				</div>
			</div>
	<!-- //new_arrivals -->
	  	<!--/slider_owl-->

			<div class="w3_agile_latest_arrivals">
				<h3 class="wthree_text_info">Similar <span>Products</span></h3>
				<?php foreach ($products as $key => $value): ?>
					<div class="col-md-3 product-men">
						<div class="men-pro-item simpleCart_shelfItem">
							<div class="men-thumb-item">
								<?php $profileImage=\App\Media::where('productId',$value->id)->first(); ?>
								@if(!empty($profileImage))
								<img src="{{asset('product/images/').'/'.$profileImage->mediaPath}}" width="75px" height="auto" class="pro-image-front" />
								<img src="{{asset('product/images/').'/'.$profileImage->mediaPath}}" width="75px" height="auto" class="pro-image-back" />
								@else
								<i class="ti-view-list-alt"></i>
								@endif
									<div class="men-cart-pro">
										<div class="inner-men-cart-pro">
											<a href="single.html" class="link-product-add-cart">Quick View</a>
										</div>
									</div>
									<span class="product-new-top">New</span>
							</div>
							<div class="item-info-product ">
								<h4><a href="/products/<?php echo $value->id; ?>">{{$value->productName}}</a></h4>
								<?php
								$rates = \App\Reviewandrating::where('toProductId', $value->id)->get();
								if (!$rates->isEmpty()) {
									$count = \App\Reviewandrating::where('toProductId', $value->id)->count();
									$stars = 0;
									foreach ($rates as $key => $value1) {
										$stars = $stars + $value1->stars;
									}
									$avg = $stars / $count;
									$fullStars = $avg*10;
									$halfStar = 0;
									if ($fullStars%10 > 0) {
									 $halfStar = 1;
									}
									$fullStars = floor($avg);
									$starCount = $fullStars + $halfStar;
									$remain = 5 - $starCount;
									for ($i=0; $i < $fullStars; $i++) {
										echo '<i class="fas fa-star starChecked" style="font-size:15px;"></i>';
									}
									for ($i=0; $i < $halfStar; $i++) {
										echo '<i class="fas fa-star-half-alt starChecked" style="font-size:15px;></i>';
									}
									for ($i=0; $i < $remain; $i++) {
										echo '<i class="fas fa-star starUnchecked" style="font-size:15px;"></i>';
									}
									echo "<br><small>($count Reviews)</small>";
								}
								?>
								<div class="info-product-price">
									<span class="item_price">Rs {{$value->productTotalPrice}}</span>
									<del>Rs {{$value->productUnitPrice}}</del>
									<?php
									$discount = $value->productUnitPrice-$value->productTotalPrice;
									?>
								</div>
							</div>
						</div>
					</div>
				<?php endforeach; ?>
				<div class="clearfix"> </div>
					<!--//slider_owl-->
		  </div>
	  </div>
 </div>
@endsection