routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/websiteDeals', 'HomeController@websitedeal');
Route::get('/deal/{category}/{id}', 'DealController@dealsInCategory');
Route::get('/product/{category}/{id}', 'ProductController@productsInCategory');
Auth::routes();
Route::get('/logout', function(){
    if (Auth::user()) {
     Auth::logout();
     return view('welcome');
  }
});
Route::get('/dashboard','HomeController@dashboard');
Route::get('/home', 'HomeController@index');
Route::get('/cart', 'HomeController@cart');
Route::get('/contact', 'FrontController@contact');
Route::post('/sendMail', 'FrontController@sendMail');
Route::post('/order/address-contact', 'OrdermetaController@addressescontacts');
Route::get('/favourite/{type}','FavouriteController@favourites');
Route::get('/reviewandrating/{id}/{type}','ReviewandratingController@reviewrate');
Route::get('/flaged/{type}','FlagController@flaged');
Route::get('/websiteBids','BidController@websiteBids');
Route::get('/user/{id}/statusNeedChange','UserController@statusNeedChange');
Route::get('/getBids/{assetbid_id}', 'BidController@getBids');
Route::get('/assetbid/viewDetails/{assetbid_id}', 'BidController@getBidsOfAsset');
Route::post('/addMapLink', 'UserController@addMapLink');
Route::post('/deleteGoogleMapsLink', 'UserController@deleteGoogleMapsLink');
Route::resource('/users', 'UserController');
Route::resource('/addresses','AddressController');
Route::resource('/category','CategoryController');
Route::resource('/contacts','ContactController');
Route::resource('/deals','DealController');
Route::resource('/favourite','FavouriteController');
Route::resource('/media','MediaController');
Route::resource('/message','MessageController');
Route::resource('/messagemedia','MessagemediaController');
Route::resource('/order','OrdermetaController');
Route::resource('/products','ProductController');
Route::resource('/reviewandrating','ReviewandratingController');
Route::resource('/subcategory','SubcategoryController');
Route::resource('/support','SupportController');
Route::resource('/supportmedia','SupportmediaController');
Route::resource('/productindeals','ProductindealController');
Route::resource('/flag','FlagController');
Route::resource('/front','FrontController');
Route::resource('/bid','BidController');
Route::resource('/assetbid','AssetBidController');
Route::resource('/livecomment','LivecommentController');

app/Reviewandrating.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Reviewandrating extends Model
{
  protected $table = 'reviewandratings';

}

app/Http/Controllers/ReviewandratingController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Auth;
use \App\Deal;
use Illuminate\Support\Facades\Input;
use \App\Product;

class ReviewandratingController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {
    $authenticatedUser=Auth::User();
    $message= "Showing all Reviews/Ratings";
      if($authenticatedUser->role == 'Super'){
        $data= \App\Reviewandrating::all();
        return view('reviewandrating.index', compact('data','message'));
      }
      elseif($authenticatedUser->role == 'Admin'){
        return View('dashboard');
      }
      elseif ($authenticatedUser->role == 'Client') {
        $orders = \App\Order::where('orderByUserId', Auth::id())->where('orderStatus', 'Complete')->get();

        $orderMetas = array();
        $products = array();
        $deals = array();
        foreach ($orders as $key => $value) {
          $orderMetas = \App\Ordermeta::where('orderId', $value->id)->get();
          foreach ($orderMetas as $key => $meta) {
            if (!empty($meta->productId)) {
              $reviewCheck = \App\Reviewandrating::where('toProductId', $meta->productId)->where('byUserId', Auth::id())->get();
              if ($reviewCheck->isEmpty()) {
                $products[] = \App\Product::findOrFail($meta->productId);
              }
            }
            else{
              $reviewCheck = \App\Reviewandrating::where('todealId', $meta->dealId)->where('byUserId', Auth::id())->get();
              if ($reviewCheck->isEmpty()) {
                $deals[] = \App\Deal::findOrFail($meta->dealId);
              }
            }
          }
        }
        return View('reviewandrating.index', compact('deals','message', 'products'));
      }
      else{
        return View('auth.login');
      }
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
    if(Auth::User()){
      return View('reviewandrating.create');
    }else{
      return View('auth.login');
    }
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request)
  {
    if(Auth::User()){
      $rate = new \App\Reviewandrating;
      $rate->stars = $request->get('rating');
      $rate->reviewPath = $request->get('review');
      if($request->get('type')=='Deal'){
        $rate->toDealId = $request->get('toDealId');
      }
      else if($request->get('type')=='Product'){
        $rate->toProductId = $request->get('toProductId');
      }
      $rate->byUserId = Auth::id();
      $rate->status = 'Active';
      $rate->save();
      $message= "One Data Successfully saved";
      if($request->get('type')=='Deal'){
        $data= \App\Deal::findOrFail($request->get('toDealId'));
        $assetcategories = \App\AssetCategory::where('dealId', $request->get('toDealId'))->get();
        foreach ($assetcategories as $key => $value) {
          if ($key==0) {
            $categories = \App\AssetCategory::where('categoryId',$value->categoryId)->get();
          }
          else{
            $result = \App\AssetCategory::where('categoryId',$value->categoryId)->get();
            $categories = $categories->merge($result);
          }
        }
        $count=0;
        foreach ($categories as $key => $value) {
          if ($value->dealId!=$request->get('toDealId')) {
            $result = \App\AssetCategory::where('categoryId', $value->categoryId)->where('dealId','!=',$request->get('toDealId'))->get();
            if ($count==0) {
              $similarDeals = $result;
              $count++;
            }
            else{
              $similarDeals = $similarDeals->merge($result);
            }
          }
        }

        $deals = array();
        $dealids = array();
        if (!$similarDeals->isEmpty()) {
          foreach ($similarDeals as $key => $value) {
            if (!in_array($value->dealId, $dealids)) {
              $dealids[] = $value->dealId;
              $deals[] = \App\Deal::findOrFail($value->dealId);
            }
          }
        }
        return View('deal.show',compact('data','message','deals'));
      }
      else if($request->get('type')=='Product'){
        $data= \App\Product::findOrFail($request->get('toProductId'));
        $assetcategories = \App\AssetCategory::where('productId', $request->get('toProductId'))->get();
        foreach ($assetcategories as $key => $value) {
          if ($key==0) {
            $categories = \App\AssetCategory::where('categoryId',$value->categoryId)->get();
          }
          else{
            $result = \App\AssetCategory::where('categoryId',$value->categoryId)->get();
            $categories = $categories->merge($result);
          }
        }
        $count=0;
        $similarProducts = \App\AssetCategory::where('categoryId', $value->categoryId)->where('productId','!=',$request->get('toProductId'))->get();
        foreach ($categories as $key => $value) {
          if ($value->productId!=$request->get('toProductId')) {
            $result = \App\AssetCategory::where('categoryId', $value->categoryId)->where('productId','!=',$request->get('toProductId'))->get();
            if ($count==0) {
              $similarProducts = $result;
              $count++;
            }
            else{
              $similarProducts = $similarProducts->merge($result);
            }
          }
        }

        $products = array();
        $productids = array();
        if (!$similarProducts->isEmpty()) {
          foreach ($similarProducts as $key => $value) {
            if (!in_array($value->productId, $productids)) {
              $productids[] = $value->productId;
              $products[] = \App\Product::findOrFail($value->productId);
            }
          }
        }
        return View('product.show',compact('data','message','products'));
      }
    }else{
      return View('auth.login');
    }
  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function show($id)
  {
    if(Auth::User()){
      $data= \App\Reviewandrating::findOrFail($id);
      $message= "One data Requested";
      return view('reviewandrating.show',compact('data','message'));
    }else{
      return View('auth.login');
    }
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function edit($id)
  {
    if(Auth::User()){
    $data = Reviewandrating::findOrFail($id);
    $message= "One data Requested";
    return view('reviewandrating.edit', compact('data','message'));
    }else{
      return View('auth.login');

    }
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, $id)
  {
    if(Auth::User()){
    $data = \App\Reviewandrating::findOrFail($id);
    $input = Request::all();
    $data->update($input);
    $message="One data updated";
    return view('reviewandrating.show',compact('data','message'));
    }else{
      return View('auth.login');
    }
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function destroy($id)
  {
    if(Auth::User()){
    $data = \App\Reviewandrating::findOrFail($id);
    $data->delete();
    $message="One data deleted";
    $data= \App\Reviewandrating::all();
    return View('reviewandrating.index',compact('data','message'));
    }else{
      return View('auth.login');
    }
  }

  public function reviewrate($id, $type){
    if (Auth::User()->role=='Client') {
      if ($type=='deal') {
        $data= \App\Deal::findOrFail($id);
        $message= "Rate";
        $assetcategories = \App\AssetCategory::where('dealId', $id)->get();
        foreach ($assetcategories as $key => $value) {
          if ($key==0) {
            $categories = \App\AssetCategory::where('categoryId',$value->categoryId)->get();
          }
          else{
            $result = \App\AssetCategory::where('categoryId',$value->categoryId)->get();
            $categories = $categories->merge($result);
          }
        }
        $count=0;
        foreach ($categories as $key => $value) {
          if ($value->dealId!=$id) {
            $result = \App\AssetCategory::where('categoryId', $value->categoryId)->where('dealId','!=',$id)->get();
            if ($count==0) {
              $similarDeals = $result;
              $count++;
            }
            else{
              $similarDeals = $similarDeals->merge($result);
            }
          }
        }

        $deals = array();
        $dealids = array();
        if (!$similarDeals->isEmpty()) {
          foreach ($similarDeals as $key => $value) {
            if (!in_array($value->dealId, $dealids)) {
              $dealids[] = $value->dealId;
              $deals[] = \App\Deal::findOrFail($value->dealId);
            }
          }
        }
        return view('deal.show',compact('data','message','deals'));
      }
      else if($type=='product'){
        $data= \App\Product::findOrFail($id);
        $message= "Rate";
        $assetcategories = \App\AssetCategory::where('productId', $id)->get();
        foreach ($assetcategories as $key => $value) {
          if ($key==0) {
            $categories = \App\AssetCategory::where('categoryId',$value->categoryId)->get();
          }
          else{
            $result = \App\AssetCategory::where('categoryId',$value->categoryId)->get();
            $categories = $categories->merge($result);
          }
        }
        $count=0;

resources/views/reviewandrating/index.blade.php
@extends('layouts.dashboard')
@section('title','Dashboard')
@section('content')
<div class="content">
    <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
              <div class="card">
                  <div class="header">
                      <h4 class="title">Review and Ratings</h4>
                      <p class="category">Records regarding Review/Rating table</p>
                  </div>
                  <div class="content table-responsive table-full-width">
                      <table class="table table-striped">
                        @if(Auth::User()->role=='Super')
                        <thead>
                          <tr>
                            <th>Id</th>
                            <th>Item Name</th>
                            <th>Type</th>
                            <th>Reviewed By</th>
                            <th>Actions</th>
                          </tr>
                        </thead>
                        <tbody>
                          <?php foreach ($data as $key => $value): ?>
                            <tr>
                              <td>{{$value->id}}</td>
                              <?php
                              if (!empty($value->toProductId)) {
                                $item = \App\Product::findOrFail($value->toProductId);
                                $type = 'Product';
                              }
                              else{
                                $item = \App\Deal::findOrFail($value->toDealId);
                                $type = 'Deal';
                              }
                              $user = \App\User::findOrFail($value->byUserId);
                              ?>
                              @if($type=='Product')
                              <td><a href="/products/<?php echo $item->id; ?>">{{$item->productName}}</a></td>
                              <td>{{$type}}</td>
                              @else
                              <td><a href="/deals/<?php echo $item->id; ?>">{{$item->dealName}}</a></td>
                              <td>{{$type}}</td>
                              @endif
                              <td><a href="/users/<?php echo $user->id;?>">{{$user->name}}</a></td>
                              <td>
                                <a href="/reviewandrating/<?php echo $value->id; ?>" class="btn btn-success">View</a>
                                <form action="{{ route('reviewandrating.destroy', $value->id) }}" method="post" style="display:inline">
                                {{ method_field('DELETE') }}
                                {{ csrf_field() }}
                                <input type="submit" class="btn btn-danger" placeholder="Delete" value="Delete"/>
                              </form>
                              </td>
                            </tr>
                          <?php endforeach; ?>
                        </tbody>
                        @endif
                        @if(Auth::User()->role=='Client')
                          <thead>
                            <th>Title</th>
                            <th>Actions</th>
                          </thead>
                          <tbody>
                            @foreach($deals as $info)
                              <tr>
                                <td>{{$info->dealName}}</td>
                                <td>
                                  <a href="/deals/<?php echo $info->id; ?>" class="btn btn-success">View</a>
                                  <a href="/reviewandrating/<?php echo $info->id; ?>/deal" class="btn btn-info">Review/Rate</a>
                                </td>
                              </tr>
                            @endforeach
                            @foreach($products as $product)
                              <tr>
                                <td>{{$product->productName}}</td>
                                <td>
                                  <a href="/products/<?php echo $product->id; ?>" class="btn btn-success">View</a>
                                  <a href="/reviewandrating/<?php echo $product->id; ?>/product" class="btn btn-info">Review/Rate</a>
                                </td>
                              </tr>
                            @endforeach
                          </tbody>
                          @endif
                      </table>
                  </div>
              </div>
          </div>

        </div>
    </div>
</div>

@endsection
@section('icon')
'ti-user'
@endsection
@section('message')
"<?php echo $message;?>"
@endsection
@section('barcolor')
'success'
@endsection

resources/views/reviewandrating/show.blade.php
@extends('layouts.dashboard')
@section('title','Dashboard')
@section('content')
@if(Auth::User()->role == 'Super')
<div class="content">
    <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
                <div class="card">
                    <div class="header">
                      <?php
                      if (!empty($data->toProductId)) {
                        $item = \App\Product::findOrFail($data->toProductId);
                        $type = 'Product';
                      }
                      else {
                        $type = 'Deal';
                        $item = \App\Deal::findOrFail($data->toDealId);
                      }

                      ?>
                        <h4 class="title">{{$data->id}}. @if($type=='Product'){{$item->productName}} @else {{$item->dealName}} @endif</h4>
                    </div>
                    <div class="content">
                      <?php
                      $stars = $data->stars;
                      for ($i=0; $i < $stars; $i++) {
                        echo '<i class="fas fa-star starChecked"></i>';
                      }
                      $remain = 5 - $data->stars;
                      for ($i=0; $i < $remain; $i++) {
                        echo '<i class="fas fa-star starUnchecked"></i>';
                      }
                      ?>
                      <p>{{$data->reviewPath}}</p>
                    </div>
                </div>
          </div>
        </div>
    </div>
</div>
@endif
@endsection
@section('icon')
'ti-user'
@endsection
@section('message')
"<?php echo $message;?>"
@endsection
@section('barcolor')
'success'
@endsection